services:
  frontend:
    build: ./file-data-analyzer-ui
    container_name: file-data-analyzer-ui
    cpus: 2
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    build: ./file-data-analyzer-api
    container_name: file-data-analyzer-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - my-network

  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - /root/mongo-backup:/data/db # Replace the path with your volume for backup
    networks:
      - my-network
    command: sudo mongod --bind_ip 127.0.0.1

networks:
  my-network:
    driver: bridge
